student_count = 11
puts "The students of Villains Academy"
puts "--------------------------------"
puts "Dr. Hannibal Lacter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"
print "Overall, we have #{11} great students \n"
print "#{student_count} great students"